from typing import Any, Protocol, runtime_checkable

from ..models.graph import QuipuNode


@runtime_checkable
class SnapshotStorage(Protocol):
    def get_tree_hash(self) -> str: ...

    def capture_workspace(self, message: str | None = None) -> str: ...

    def restore_workspace(self, tree_hash: str) -> None: ...

    def read_blob(self, blob_hash: str) -> bytes: ...

    def read_tree_blobs(self, tree_hash: str) -> dict[str, bytes]: ...

    def get_diff_stat(self, old_tree: str, new_tree: str, count: int = 30) -> str: ...

    def get_diff_name_status(self, old_tree: str, new_tree: str) -> list[tuple[str, str]]: ...


@runtime_checkable
class GraphIndex(Protocol):
    def record_node(self, node: QuipuNode, meta_json: str | None = None, **kwargs: Any) -> None: ...

    def get_node(self, commit_hash: str) -> QuipuNode | None: ...

    def get_node_count(self) -> int: ...

    def get_node_position(self, output_tree_hash: str) -> int: ...

    def load_nodes_paginated(self, limit: int, offset: int) -> list[QuipuNode]: ...

    def load_all_nodes(self) -> list[QuipuNode]: ...

    def find_nodes(
        self, summary_regex: str | None = None, node_type: str | None = None, limit: int = 10
    ) -> list[QuipuNode]: ...

    def get_ancestor_output_trees(self, start_output_tree_hash: str) -> set[str]: ...

    def get_descendant_output_trees(self, start_output_tree_hash: str) -> set[str]: ...

    def get_private_data(self, node_commit_hash: str) -> str | None: ...


# --- 向后兼容别名 (过渡期保留，后续阶段清理) ---


@runtime_checkable
class HistoryReader(Protocol):
    def load_all_nodes(self) -> list[QuipuNode]: ...
    def get_node_content(self, node: QuipuNode) -> str: ...
    def get_node_blobs(self, commit_hash: str) -> dict[str, bytes]: ...
    def find_nodes(
        self, summary_regex: str | None = None, node_type: str | None = None, limit: int = 10
    ) -> list[QuipuNode]: ...
    def get_node_count(self) -> int: ...
    def load_nodes_paginated(self, limit: int, offset: int) -> list[QuipuNode]: ...
    def get_ancestor_output_trees(self, start_output_tree_hash: str) -> set[str]: ...
    def get_private_data(self, node_commit_hash: str) -> str | None: ...
    def get_descendant_output_trees(self, start_output_tree_hash: str) -> set[str]: ...
    def get_node_position(self, output_tree_hash: str) -> int: ...


@runtime_checkable
class HistoryWriter(Protocol):
    def create_node(
        self, node_type: str, input_tree: str, output_tree: str, content: str, **kwargs: Any
    ) -> QuipuNode: ...
