from typing import Protocol, runtime_checkable


@runtime_checkable
class Renderer(Protocol):
    """定义消息渲染器的行为契约"""

    def success(self, message: str) -> None: ...
    def info(self, message: str) -> None: ...
    def warning(self, message: str) -> None: ...
    def error(self, message: str) -> None: ...
    def data(self, data_string: str) -> None: ...
